name: radix-velero-plugin-pr
on: [pull_request]
jobs:

  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
      id: go
    - name: Make CI
      run: make ci