name: radix-velero-plugin-build
on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  build:
    name: Build-push-radix-velero-plugin
    env:
      IMAGE: radix-velero-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
          echo "::set-output name=LATEST_TAG::${branch}-latest"
      - name: Build
        run: make local
      - name: Test
        run: make test
      - name: Build Docker image for radixdev ACR
        run: |
          docker build . -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_TAG }}
      - name: Build Docker image for radixprod ACR
        if: github.ref == 'refs/heads/release'
        run: |
          docker build . -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_TAG }}
      - name: Login to radixdev for master
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Login to ACR radixdev'
        run: |
          az acr login --name radixdev
      - name: push master to radixdev
        run: |
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_TAG }}
      - name: Login to radixprod for release
        if: github.ref == 'refs/heads/release'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: 'Login to ACR radixprod'
        if: github.ref == 'refs/heads/release'
        run: |
          az acr login --name radixprod
      - name: push release to radixprod
        if: github.ref == 'refs/heads/release'
        run: |
          docker push radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          docker push radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.LATEST_TAG }}